# Generated by Django 3.0.2 on 2020-03-27 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='quantity',
        ),
    ]
