# Generated by Django 3.0.2 on 2020-03-27 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_wish_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='description',
            field=models.TextField(max_length=100),
        ),
    ]
